[workspace]
authors = ["e-deutsch <egdeutsch@wisc.edu>"]
channels = ["conda-forge"]
name = "dir-structure"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
